; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
;Identify port by opening a terminal and using this command: ls /dev/cu.* & remember to use the correct ifdef in cubecore
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
;working for esp32's and changed for brainboard	....upload_port = /dev/tty.usbserial-0001
;working for esp32's....monitor_port = /dev/tty.usbserial-0001
;upload_port = /dev/tty.usbserial-110
;monitor_port = /dev/tty.usbserial-110
upload_speed = 115200

lib_deps =
    fastled/FastLED@^3.6.0
; 2. ADD THIS: Pull the custom Bluepad32 Arduino Core
platform_packages = 
    framework-arduinoespressif32 @ https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
build_flags =
   ; -DFASTLED_RMT_BUILTIN_DRIVER
    -DFASTLED_ALLOW_INTERRUPTS=1

;[env:uno]
;platform = atmelavr
;board = uno
;framework = arduino


; This is platformio's way of including Arduino Libraries.
;lib_deps =
;	FastLED  ; Grabs the "official" FastLED library.
	; However here we have additional flexibility in that we can pull
	; from github as well for the main branch or specific branches or commits.
	; Here is an example of pulling from the master branch of FastLED library.
	;
	; FastLED=https://github.com/FastLED/FastLED
	;
	; Here's an example of pulling from a specific branch of FastLED library.
	;
	; FastLED=https://github.com/FastLED/FastLED#somebranch
	;
	; For example, if you make a fix in the FastLED library in a forked repo
	; then you can pull from your forked repo like this.
	;
	; FastLED=https://github.com/yourusername/FastLED

